on:
  push:
    branches:
      - dev

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

name: Jekyll Label Bot
jobs:
  jekyll-label-action:
    name: Label
    runs-on: ubuntu-latest
    
    steps:
      - uses: Pandapip1/jekyll-label-action@bfc2f4c2e738017a20b4822c229f02d1db79c59b
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-path: config/.jekyll-labels.yml
